In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("loan_approval_dataset.csv")
df.head(2)

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   loan_id                    4269 non-null   int64
 1    no_of_dependents          4269 non-null   int64
 2    education                 4269 non-null   object
 3    self_employed             4269 non-null   object
 4    income_annum              4269 non-null   int64
 5    loan_amount               4269 non-null   int64
 6    loan_term                 4269 non-null   int64
 7    cibil_score               4269 non-null   int64
 8    residential_assets_value  4269 non-null   int64
 9    commercial_assets_value   4269 non-null   int64
 10   luxury_assets_value       4269 non-null   int64
 11   bank_asset_value          4269 non-null   int64
 12   loan_status               4269 non-null   object
dtypes: int64(10), object(3)
memory usage: 433.7+ KB

In [4]:
for i in df:
    print("*"*50,i,"*"*50)
    print()
    print(df[i].nunique())
    print()

************************************************** loan_id **************************************************

4269

**************************************************  no_of_dependents **************************************************

6

**************************************************  education **************************************************

2

**************************************************  self_employed **************************************************

2

**************************************************  income_annum **************************************************

98

**************************************************  loan_amount **************************************************

378

**************************************************  loan_term **************************************************

10

**************************************************  cibil_score **************************************************

601

**************************************************  residential_assets_value **************************************************

278

**************************************************  commercial_assets_value **************************************************

188

**************************************************  luxury_assets_value **************************************************

379

**************************************************  bank_asset_value **************************************************

146

**************************************************  loan_status **************************************************

2

In [5]:

# Discrete univariate non visual 
def discrete_univariate_analysis(discrete_data):
    for col_name in discrete_data:
        print("*"*10, col_name, "*"*10)
        print(discrete_data[col_name].agg(['count', 'nunique', 'unique']))
        print('Value Counts: \n', discrete_data[col_name].value_counts())
        print()

In [6]:
# Contionous univariate non visual
def numerical_univariate_analysis(numerical_data):
    for col_name in numerical_data:
        print("*"*10, col_name, "*"*10)
        print(numerical_data[col_name].agg(['count', 'min', 'max', 'mean', 'median', 'std', 'skew']))
        print()

In [7]:
discrete_df = df.select_dtypes(include = 'object')
contionus_df = df.select_dtypes(include = 'number')

In [8]:
discrete_univariate_analysis(discrete_df)

**********  education **********
count                            4269
nunique                             2
unique     [ Graduate,  Not Graduate]
Name:  education, dtype: object
Value Counts:
  education
Graduate        2144
Not Graduate    2125
Name: count, dtype: int64

**********  self_employed **********
count             4269
nunique              2
unique     [ No,  Yes]
Name:  self_employed, dtype: object
Value Counts:
  self_employed
Yes    2150
No     2119
Name: count, dtype: int64

**********  loan_status **********
count                        4269
nunique                         2
unique     [ Approved,  Rejected]
Name:  loan_status, dtype: object
Value Counts:
  loan_status
Approved    2656
Rejected    1613
Name: count, dtype: int64

In [9]:
numerical_univariate_analysis(contionus_df)

********** loan_id **********
count     4269.000000
min          1.000000
max       4269.000000
mean      2135.000000
median    2135.000000
std       1232.498479
skew         0.000000
Name: loan_id, dtype: float64

**********  no_of_dependents **********
count     4269.000000
min          0.000000
max          5.000000
mean         2.498712
median       3.000000
std          1.695910
skew        -0.017971
Name:  no_of_dependents, dtype: float64

**********  income_annum **********
count     4.269000e+03
min       2.000000e+05
max       9.900000e+06
mean      5.059124e+06
median    5.100000e+06
std       2.806840e+06
skew     -1.281443e-02
Name:  income_annum, dtype: float64

**********  loan_amount **********
count     4.269000e+03
min       3.000000e+05
max       3.950000e+07
mean      1.513345e+07
median    1.450000e+07
std       9.043363e+06
skew      3.087239e-01
Name:  loan_amount, dtype: float64

**********  loan_term **********
count     4269.000000
min          2.000000
max         20.000000
mean        10.900445
median      10.000000
std          5.709187
skew         0.036359
Name:  loan_term, dtype: float64

**********  cibil_score **********
count     4269.000000
min        300.000000
max        900.000000
mean       599.936051
median     600.000000
std        172.430401
skew        -0.009039
Name:  cibil_score, dtype: float64

**********  residential_assets_value **********
count     4.269000e+03
min      -1.000000e+05
max       2.910000e+07
mean      7.472617e+06
median    5.600000e+06
std       6.503637e+06
skew      9.784506e-01
Name:  residential_assets_value, dtype: float64

**********  commercial_assets_value **********
count     4.269000e+03
min       0.000000e+00
max       1.940000e+07
mean      4.973155e+06
median    3.700000e+06
std       4.388966e+06
skew      9.577909e-01
Name:  commercial_assets_value, dtype: float64

**********  luxury_assets_value **********
count     4.269000e+03
min       3.000000e+05
max       3.920000e+07
mean      1.512631e+07
median    1.460000e+07
std       9.103754e+06
skew      3.222075e-01
Name:  luxury_assets_value, dtype: float64

**********  bank_asset_value **********
count     4.269000e+03
min       0.000000e+00
max       1.470000e+07
mean      4.976692e+06
median    4.600000e+06
std       3.250185e+06
skew      5.607250e-01
Name:  bank_asset_value, dtype: float64

In [4]:
df = pd.read_excel('weather.xlsx')
df

    Day   Outlook Temperature Humidity    Wind Play
0     1     Sunny         Hot     High    Weak   No
1     2     Sunny         Hot     High  Strong   No
2     3  Overcast         Hot     High    Weak  Yes
3     4      Rain        Mild     High    Weak  Yes
4     5      Rain        Cool   Normal    Weak  Yes
5     6      Rain        Cool   Normal  Strong   No
6     7  Overcast        Cool   Normal  Strong  Yes
7     8     Sunny        Mild     High    Weak   No
8     9     Sunny        Cool   Normal    Weak  Yes
9    10      Rain        Mild   Normal    Weak  Yes
10   11     Sunny        Mild   Normal  Strong  Yes
11   12  Overcast        Mild     High  Strong  Yes
12   13  Overcast         Hot   Normal    Weak  Yes
13   14      Rain        Mild     High  Strong   No

 # MARGINAL PROBABLITES (SINGLE COLUMN)

# 1.what is probablity of getting rain tommorow

In [5]:
sum(df['Outlook'] == 'Rain')/ len(df)

0.35714285714285715

In [9]:
df['Outlook'].value_counts(normalize = True).loc['Rain']

np.float64(0.35714285714285715)

# 2.What is the probablity of playing cricket tommorow

In [13]:
df['Play'].value_counts(normalize = True).loc['Yes']

np.float64(0.6428571428571429)

# 3.waht is the probability that temperature is not cool tommorow

In [22]:
(df['Temperature'].value_counts(normalize = True).loc['Cool'])

np.float64(0.2857142857142857)

# Join Probablity

# What is the probablity of playing cricket and temperature is hot ?

In [26]:
sum((df['Play'] == 'Yes') & (df['Temperature'] == 'Hot'))/len(df)

0.14285714285714285

In [31]:
pd.crosstab(index =df['Play'], columns =df['Temperature'], normalize = True).loc[['Yes'],['Hot']]

Temperature       Hot
Play
Yes          0.142857

# What is the probablity of humidity is normal and temperature is cool

In [33]:
sum((df['Humidity']=='Normal')& (df['Temperature']== 'Cool'))/len(df)

0.2857142857142857

In [34]:
pd.crosstab(index = df['Humidity'],columns = df['Temperature'],normalize = True).loc[['Normal'],['Cool']]

Temperature      Cool
Humidity
Normal       0.285714

# Conditional Probablity

# What is the probablity of playing cricket if in it is raining

In [36]:
pd.crosstab(index = df['Play'], columns = df['Outlook'],normalize = 'columns').loc[['Yes'],['Rain']]

Outlook  Rain
Play
Yes       0.6

# 2. What is the probablity of not getting of not playing cricket when humidity is high?

In [43]:
pd.crosstab(index = df['Humidity'], columns = df['Play'], normalize = 'index').loc[['High'],['No']]

Play            No
Humidity
High      0.571429

In [32]:
df

    Day   Outlook Temperature Humidity    Wind Play
0     1     Sunny         Hot     High    Weak   No
1     2     Sunny         Hot     High  Strong   No
2     3  Overcast         Hot     High    Weak  Yes
3     4      Rain        Mild     High    Weak  Yes
4     5      Rain        Cool   Normal    Weak  Yes
5     6      Rain        Cool   Normal  Strong   No
6     7  Overcast        Cool   Normal  Strong  Yes
7     8     Sunny        Mild     High    Weak   No
8     9     Sunny        Cool   Normal    Weak  Yes
9    10      Rain        Mild   Normal    Weak  Yes
10   11     Sunny        Mild   Normal  Strong  Yes
11   12  Overcast        Mild     High  Strong  Yes
12   13  Overcast         Hot   Normal    Weak  Yes
13   14      Rain        Mild     High  Strong   No